spring:
  application:
    name: spring-ai-gemini-chatbot
  ai:
    vertex:
      ai:
        gemini:
          project-id: <seu-projeto-gcloud>
          chat:
            options:
              model: "gemini-1.5-flash-001"
          location: "us-central1"
          transport: rest
        embedding:
          project-id: ${spring.ai.vertex.ai.gemini.project-id}
          location:  ${spring.ai.vertex.ai.gemini.location}